### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by HamptonMakes** [haml/haml#1069]
We should fix up the readme and also add in notes about the 6.x project plan.

**Comment by k0kubun** [comment]
I fixed one incorrectness that was inherited from Hamlit https://github.com/haml/haml/commit/c6e3f85a175d5b41aace36408758a4b0e7052560, but otherwise I don't see any things that need to be immediately fixed. Let's close this for now and think about it when we have bandwidth to actually work on other ideas.
