### ISSUE TITLE
How can I re-use HAML blocks?

### ISSUE THREAD

**Issue by benlieb** [haml/haml#1076]
I'd like to do something like this, that can receive arguments:

```haml
- def entry_link(url, text)
  - link_to url do
    %i.fa.fa-map
    text
```

The only way I know how to do this would be to put it in a partial. 

I got the following to work, but it isn't really acceptable

```haml
:ruby
  def entry_link(url, text)
    capture_haml(url, text) do |url, text|
      link_to url do
        haml_tag :i, {class: 'fa fa-map'}
        haml_concat(text)
      end
    end
  end
```

**Comment by k0kubun** [comment]
I'm afraid this is not how template engines could work. A template engine appends a result to a secret local variable, which is why a block works but a normal method definition doesn't. Even using `define_method` to workaround the local variable could be tricky because returning a string from a method and appending a string to a local variable are completely different and Haml can switch the behavior only for obvious cases like `each` or `times`.

It'd be really hacky to support such a feature, or there's no reasonable and optimal way to implement one unless you file such a pull request yourself. So I suggest you to define a method outside a template if you're unhappy with `:ruby`.
