### ISSUE TITLE
NoMethodError: undefined method 'haml_tag' after upgrading to version `6.0.0` from `5.2.2`

### ISSUE THREAD

**Issue by sordu** [haml/haml#1087]
**Description:**

After upgrading from version `5.2.2` to `6.0.0` the error ``NoMethodError: undefined method `haml_tag'`` occurs, where `.haml_tag()` is used.

- Rails version: `~> 6.1.6`
- Ruby version: `2.7.6`

**What I already tried:**
- Include `Haml::Helpers` explicitly in the files that use the method
- Try `haml` version [6.0.1](https://github.com/haml/haml/releases/tag/v6.0.1)
- Include [haml-rails](https://github.com/haml/haml-rails) as well

**The problem:**

It looks like that `def haml_tag` was completely removed from the gem since `lib/haml/helpers.rb` was deleted/refactored:
- https://github.com/haml/haml/compare/v5.2.2...v6.0.0#diff-e478c5b6521eb9138e8edbb3480fb83783455bae40d1069f324ca23158b1b4f1L488
- https://www.rubydoc.info/gems/haml/Haml/Helpers

How could I solve this problem?

**Comment by k0kubun** [comment]
I'm sorry for your migration effort, but this is intentional and a wont-fix. We believe that helpers shouldn't be the responsibility of a template engine for performance reasons. You should be able to ask web frameworks to provide them or define them yourself in your application. For `haml_tag`, we often recommend using `content_tag` for Rails users.
