### ISSUE TITLE
HAML 6 : cannot yield blocks as expression any more

### ISSUE THREAD

**Issue by mildred** [haml/haml#1103]
The following code worked with HAML 5 and is no longer working:

```haml
= helper_method(capture do
  %div
  = foo
- end, foo: :bar)
```

The error: *syntax error, unexpected `end', expecting end-of-input*

**Comment by k0kubun** [comment]
I don't think we've ever intended to officially support the syntax of the `- end, foo: :bar)` line unless you find an old document that specifically recommends it. Haml is a nest-based syntax where each construct starts with a leading line followed by deeper lines. Any script followed by `-` should make sense by itself whereas `end, foo: :bar)` doesn't.

For that code, I would update the definition of `helper_method` and rewrite it like:

```haml
= helper_method(foo: :bar) do
  %div
  = foo
```

Also, next time please try providing a template that actually works without extra dependency. You didn't provide any repository or a script to reproduce the issue, so I don't know how to correctly render it even with Haml 5 because I don't know what `helper_method` and `capture` are, and we can't provide any better feedback than this.
