### ISSUE TITLE
HAML 6 yields duplicate markup with view helpers

### ISSUE THREAD

**Issue by mildred** [haml/haml#1104]
With HTML6 I get some duplicate markup with some view helpers that I use (notably https://github.com/thooams/ui_bibz).

I could reproduce the issue with a minimal HAML template:

```haml
= "bar"
- s = Struct.new('Test') do
  - include ActionView::Helpers
  - attr_accessor :output_buffer
  - def render(&blc) = form_for('form', url: '#', &blc)
= s.new.render do
  .empty inside
= "baz"
```

This should show `bar inside baz` but instead it shows `bar inside bar inside baz`

edit: the problem can be further simplified by replacing `form_for()` with `capture()`, and the problem does not appear if capture is replaced by with_output_buffer

**Comment by mildred** [comment]
The issue seems to be caused by the fact that now HAML blocks returns the full buffer since the beginning of the template and not the part relevant to the block.

The following block:

```haml
- do
  .empty inside
```

When called from within the helper, it returns "\nbar\n<div class='empty'>inside</div>\n"

**Comment by mildred** [comment]
Minimal reproducer:

```haml
= "bar"
- cls = Struct.new('Test') do
  - def render3(&blc); blc.call ; end
- val = cls.new
= val.render3 do
  .empty inside
= "baz"
````

**Comment by mildred** [comment]
Solution is to use `with_output_buffer` in the template context:

```haml
= " bar "
- def helper(val, &blc); val.render3 { with_output_buffer(&blc) }; end
- cls = Struct.new('Test') do
  - def render3(&blc); ['a', blc.call, 'z'].join(' ').html_safe; end
- val = cls.new
= helper(val) do
  .empty inside
= " baz "
```

**Comment by mildred** [comment]
If ActionView is not available in the context, it's possible to find it in the binding:

```haml
= " bar "
- def helper(val, &blc); val.render3(&blc); end
- cls = Struct.new('Test') do
  - def render3(&blc); ['a', blc.binding.receiver.with_output_buffer(&blc), 'z'].join(' ').html_safe; end
- val = cls.new
= helper(val) do
  .empty inside
= " baz "
```

**Comment by k0kubun** [comment]
This is intentional from Haml 6 and going forward. I added a relevant changelog entry for you https://github.com/haml/haml/commit/68717aa3299271436ea5a828ca454e2b924c1c7e.

It's a trade-off that made Haml 6 faster than Haml 5. The details are described at https://github.com/k0kubun/hamlit/issues/191#issuecomment-1222727863. To make `- foo.each do |bar|` work, capturing a block nested by `- foo = bar do` is not possible without hacking the buffer, which is very slow, and Haml 6 is not longer that framework. This is the same design as Slim, which is why it's as fast as Slim today.

**Comment by mildred** [comment]
Thank you :)
