### ISSUE TITLE
omitted value in select option now looks like boolean

### ISSUE THREAD

**Issue by arnisoft** [haml/haml#1106]
`%option(value) test`

Haml 5:
`<option value>test</option>`

Haml 6:
`<option value="true">test</option>`

**Comment by k0kubun** [comment]
This is intentional in Haml 6 and going forward. I updated a changelog entry to make it a bit clearer https://github.com/haml/haml/commit/8610dc1824c55fa024f28f2adf952be12a83c10b.

In Haml, `%option(value)` is the same as `%option{ value: true }`. Only boolean attributes behave like `value` (a boolean attribute) instead of `value="true"` (NOT a boolean attribute), and it was changed because `value` is no longer handled as a boolean attribute. 

If you want to make something a boolean attribute, please bring a reference that says it's a boolean attribute. We've used https://www.w3.org/TR/xhtml1/guidelines.html and https://html.spec.whatwg.org/ so far, and the current list of `Haml::AttributeBuilder::BOOLEAN_ATTRIBUTES` has been based on those references.
