### ISSUE TITLE
Can one define user tags

### ISSUE THREAD

**Issue by lemmuh** [haml/haml#1111]
Hello,

in former times there was gem called haml_user_tags.

However, this gem is outdated. 

Is there a possibility to define user tags inside this gem

**Comment by k0kubun** [comment]
No. From Haml 6 onwards, we will only scope out helpers from supported features because it should be a web framework's responsibility to make it performant, e.g. Rails, Sinatra. Please define helper methods on the view context that you're using, instead of trying to inject the implementation from Haml-generated code.
