### ISSUE TITLE
Syntax highlighting in REFERENCE.md

### ISSUE THREAD

**Issue by Frigory33** [haml/haml#1126]
Hello,

As you can see in the [Custom filters](https://haml.info/docs/yardoc/file.REFERENCE.html#custom-filters) section of the REFERENCE, syntax highlighting for Ruby code hasn’t worked at all.

Also, what about enabling syntax highlighting for HTML and Haml codes in the REFERENCE? [On Wikipedia](https://en.wikipedia.org/wiki/Haml), you can see they’re colored…

**Comment by k0kubun** [comment]
Thank you for reporting this. Since it's rendering fine on GitHub, I think it's the fault of https://github.com/haml/haml-site that https://haml.info is broken. Could you move this issue to that repository instead?

**Comment by Frigory33** [comment]
Where is the REFERENCE in https://github.com/haml/haml-site actually? I’m not able to find it…

**Comment by k0kubun** [comment]
IIUC it takes REFERENCE.md from this repository and converts that there. So it doesn't need to reside in that repository. However, as long as the conversion logic is in that repository, it's something that shouldn't be addressed in this repository.

Since you filed an issue there, I'm closing this. Thank you!
