### ISSUE TITLE
Mustache-alike generation.

### ISSUE THREAD

**Issue by adamsalter** [haml/haml#43]
Raising an issue to open discussion. I don't know either Haml or [Mustache](http://github.com/defunkt/mustache) codebase well enough to start work on this straight away.

Chris Wanstrath (aka defunkt) has just released a great template engine 'Mustache' based on Google's CTemplate.

As a templating solution Mustache is great, but I don't think anybody can deny the cleanness and readability of HAML code.

I don't think it would be too difficult to modify HAML to support Mustache-like generation. This could even be an option on HAML which could be turned on an off.

I'm thinking something like:

a) no ruby code evalution, so (-, =) no longer evaluate.

b) new syntax `{{#boolean}}`, `{{helper}}`, `{{{non_interpreted_helper}}}` can be used anywhere in the code(ie as nodes and inside text nodes) and will be evaluated as expected.

c) integration into rails could be very simple. All template logic now goes into the helpers files.

**Comment by k0kubun** [comment]
It passed 8 years. Closing for now but feel free to reopen this.

**Comment by k0kubun** [comment]
In vue.js, what kind of input and output do you want in Haml? And which Haml feature prevents that?

**Comment by StevenTheEVILZ** [comment]
Haml outputs erb using its equal-sign shorthand, vuejs uses mustache syntax. 

So here's what haml will output for erb: `%h1= message` => `<h1><%= message %></h1>`

Whereas if you were to use vuejs, it would be ideal (but not neccecary and probably not hard to implement as a config feature) if it did this:
`%h1= message` => `<h1> {{ message }} </h1>`

**Comment by k0kubun** [comment]
> Haml outputs erb using its equal-sign shorthand, vuejs uses mustache syntax.
> So here's what haml will output for erb: `%h1= message => <h1><%= message %></h1>`

In precise, Haml doesn't output erb. It outputs just Ruby code. But probably I know what you mean.

> Whereas if you were to use vuejs, it would be ideal (but not neccecary and probably not hard to implement as a config feature) if it did this:
> `%h1= message => <h1> {{ message }} </h1>`

Now we have code generator layer in Haml. At first I can do that easily as you say. But it was not that truth.

In the layer for `message`, we have `::Haml::Helpers.html_escape(..)` for html_escape, `.to_s` to render correctly as old behavior, `"_hamlout.attributes({ \"foo\".freeze => _haml_attribute_compiler1 }, nil)"` to render dynamic attributes. 

So, you can get the behavior in a "not hard to implement" way.

## input
```haml
%h1= message
```

## expected output
```html
<h1>{{message}}</h1>
```

## actual output (for Sinatra, not HTML-escaped by default)
```html
<h1>{{((message
).to_s).to_s}}</h1>
```

## actual output (for Rails, HTML-escaped by default)
```html
<h1>{{(_hamlout.fix_textareas!(::Haml::Helpers.html_escape(((message
)).to_s));).to_s}}</h1>
```

I think this is not what you want.

Then, we need to create "Temple filter" to change that behavior and combine Haml's original Temple filters with them. But it'll require many sources limited for that feature. Thus I agree with nex3 in the point that "this would make the most sense as a separate library".

Again, as nex3 said, this should be implemented as a separate library, and it is possible now because we implemented Haml with Temple. Thus it's welcomed to create such gem. But I'm not using vue.js for now and I have no motivation to create that.

**Comment by k0kubun** [comment]
Since now it's not issue for Haml gem itself, closing. The reporting comment to create such gem would be appreciated if someone achieves it.

**Comment by StevenTheEVILZ** [comment]
K
