### ISSUE TITLE
Syntax checker doesn't verify ruby part of syntax

### ISSUE THREAD

**Issue by CGamesPlay** [haml/haml#762]
When running `haml -c` to verify that no syntax errors are in a haml file, haml only precompiles the template, but does not attempt to validate that the syntax of the resulting code. This leads to hard-to-understand errors and `haml -c` producing misleading output.

It would be nice for haml to verify that the precompiled code is parseable by ruby. A function like this could be used as a predicate to validate the syntax of the overall template:

```ruby
def valid_syntax?(code)
  eval("return true\n#{code}")
rescue SyntaxError
  false
end
```

Here is a transcript showing what I mean:

```
$ cat test.haml
= -

$ haml -c test.haml
Syntax OK

$ haml test.haml
Syntax error on line 131: test.haml:2: syntax error, unexpected ')'
));}\n", 0, false);;_erbout
 ^
test.haml:2: unterminated string meets end of file
test.haml:2: syntax error, unexpected $end, expecting ')'
));}\n", 0, false);;_erbout
                           ^
  Use --trace for backtrace.
```

**Comment by norman** [comment]
I've made this change in the least-invasive way possible. Currently when running `bin/haml -d <file>`, Haml will print the compiled Ruby code and then execute it. I've made the command instead check the code for errors using code similar to the sample provided by @mattwildig. Note that I was unable to successfully rescue from SyntaxError for reasons I don't understand, and so the code rescues from `Exception`.

If anybody has feedback on this please reopen, otherwise I'm closing now to try to get towards my utopian goal of Issues-zero.

**Comment by mattwildig** [comment]
The reason you couldn’t rescue `SyntaxError` is that since that code is inside the `Haml` module, `SyntaxError` refers to `::Haml::SyntaxError`, not `::SyntaxError` which we want. I’ve changed it to rescue `::SyntaxError`.

It took a while to track that one down, it was a bit of a facepalm moment when I figured out what was happening.

**Comment by norman** [comment]
Double facepalm over here. Thanks for having my back.
