### ISSUE TITLE
Set style attribute though hash.

### ISSUE THREAD

**Issue by cirosantilli** [haml/haml#787]
I want to write:

```
%div{ style: { display: "none", width: "50px" } }
```

To produce:

```
<div style="display:none; width:50px;">
```

This would be a special case for the `style` key, like the one existing for `class: ["class1", "class2"]` and `id: ["a", "b"]`.

**Comment by bogdan** [comment]
I have encountered this problem in my project. My specific is that many CSS styles are defined by values in the DB. The most often ones are `width` and `height`: they can not be styled with CSS classes because value is stored in db.
I have to always write that manipulation of transforming hash style into string myself.

@norman's concern regarding extension and supporting more CSS features:
 Further improvements of a feature is absolutely optional. Using Hash doesn't make it inflexible in any way.  We already support `data` attribute special case. Why did we do that? Why the same reason can not serve for `style` ?

**Comment by norman** [comment]
I don't think this feature would be a big win, look at the difference:

```haml
%div{ style: { display: "none", width: "50px" } }
``` 
versus:

```haml
%div{ style: "display: none; width: 50px" }
```

For data attributes, it's a bigger win because it's more terse and lets you use Ruby 1.9-style hash keys for attribute names that use hyphens. Compare:

```haml
%div{ data: { foo: "bar", something: "else" } }
```

to:

```haml
%div{"data-foo" => 'bar', "data-something" => "else"}
```
In your case @bogdan you can also use interpolation to insert the values you need:

```haml
%div{ style: "display: #{@foo.display}; width: #{@foo.width}'  }
```
You might also want to use a `:css` filter for this, you can also use interpolation there.

You might also want to write a helper method for this and use it throughout your app:

```ruby
def cssify(hash={})
  hash.inject([]) do |memo, object|
    memo << object.join(": ")
  end.join("; ")
end
```

```haml
%div{ style: cssify(display: "none", width: "50px") }
``` 

The style attribute is also something that should be used sparingly; another thing that makes me less willing to build a feature around it unless there was a really clear win for a lot of users.

**Comment by bogdan** [comment]
This is exactly what I do now:

``` haml
%div{ style: cssify(display: "none", width: "50px") }
```

And I need to cssify all the time. 
I consider using hash for data is more beneficial and harder to support while style is less beneficial and easier to support.

There must a thing moving HTML forward making it more semantic. And I think HAML is a place where it should happen. If HAML is already a conservative software where syntax is not changing, that is ok.
But here we are not talking about any visible overhead at all.

**Comment by norman** [comment]
> And I need to cssify all the time. 

If you're leaning so heavily on style attributes that you have to do it so many places that it's a burden, then I think that's an indication of a problem in your application architecture, not of feature missing from Haml.

But if you feel very strongly about this, then why don't you implement it in Haml and send a pull request. If the changes are indeed small and enough people want it then I'd be willing to reconsider.
