### ISSUE TITLE
Reducing SafeBuffer allocations

### ISSUE THREAD

**Issue by jdelStrother** [haml/haml#796]
Hi there - I'm looking into reducing the number of ruby objects that our app allocates on each request - it's currently standing at around 400k objects, which seems excessive.  A lot of them are SafeBuffers from haml templates.

Given a trivial erb template: 

``` erb
<div style="color: blue">hi</div>
```

There's only one SafeBuffer created, for `@output_buffer`

The corresponding haml template:

``` haml
%div{style: 'color: blue'}
  hi
```

creates 3 SafeBuffers - one for `@output_buffer`, one for "color: blue", and another from the template return value (`::Haml::Util.html_safe(__erbout)`).

This is a somewhat unfair comparison - that example ERB template isn't even doing any interpolation, so may as well be plain text - but I can't figure out how you'd get HAML to do less work.  Is there any way of expressing element attributes in HAML that doesn't require each individual attribute to be converted to a SafeBuffer?

I'm also struggling to see why the 3rd SafeBuffer is necessary in addition to the first one, when ERB seems to manage without it.  Any hints?

**Comment by k0kubun** [comment]
Haml's buffer is not something compatible with SafeBuffer. It's `Haml::Buffer`. We can't achieve some of the features without `Haml::Buffer`.

So we should have `Haml::Buffer` and its conversion to SafeBuffer for Haml-specific rendering, which is 3rd you mentioned. And 1st `ActionView::OutputBuffer` is necessary to work with Rails because `Haml::Buffer` is not compatible with `ActionView::OutputBuffer`. While I think there should be better solution than current behavior, I don't have any idea yet.

2nd is something to be resolved. Haml does such optimization and I'm sure its support is improved in https://github.com/haml/haml/pull/904. Please try Haml 5.0.0.beta.2.
