### ISSUE TITLE
collapse_whitespace

### ISSUE THREAD

**Issue by Exoth** [haml/haml#825]
The `remove_whitespace` option removes absolutely all whitespaces, which results in different page rendering. It would be nice to have an option to replace all double, triple etc. whitespaces by a single whitespace. So enabling this option would not change rendering but would reduce page size.

**Comment by norman** [comment]
Sounds reasonable. Are you willing to work on this?

**Comment by Exoth** [comment]
Probably I'll be able to get to it in a week or so.

**Comment by norman** [comment]
Great! One thing to keep in mind, we don't want to add too many more configuration options to Haml. I would suggest making a "whitespace" option that takes arguments like "squeeze" or "strip" rather than having two options, "remove_whitespace" and "collapse_whitespace". I suggest "squeeze" and "strip" rather than "collapse" and "remove" since those match up more closely how Ruby's `String#squeeze" and `String#strip`.

If you implement the feature, we can then help you incorporate it into Haml in a way that deprecates the current options and enables the new ones in a way that works with our release planning.

**Comment by Exoth** [comment]
I would prefer to have just one option too, though it will probably make this feature have to be included only in the next major release.

**Comment by Exoth** [comment]
Ah, as the name of option is different, that it will be ok for minor release too, now I see.

**Comment by norman** [comment]
The next major release is coming out "soon" so I don't think this would be included, but yes - we can do this in a backwards-compatible way and add it to the next minor version.

**Comment by Exoth** [comment]
By the way, there is one more way: we can just always squeeze in ugly mode. As rendering will stay the same, this change probably can't be considered a breaking one.

**Comment by norman** [comment]
That might be pretty costly depending on when it's done. It's probably better to let people opt in to the feature rather than have it enabled by default.

**Comment by Exoth** [comment]
I'll think that I try to do some benchmarks. With more info on how costly it is it'll be easier for us to decide which approach is better.

**Comment by norman** [comment]
Sounds good.

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.

**Comment by Exoth** [comment]
Yeah, sorry that I haven't got time to make the fix.
