### ISSUE TITLE
small spelling mistake in docs

### ISSUE THREAD

**Issue by dwanderton** [haml/haml#826]
Underneath header 'Attribute Methods' change 'me' to 'be':

    All the hashes will me merged together, from left to right.

Should be:

    All the hashes will be merged together, from left to right.

viewed at http://haml.info/docs/yardoc/file.REFERENCE.html

**Comment by mattwildig** [comment]
Thanks for reporting this.

It looks like it has already been fixed in master(11a19d3821d8e0edac1b308d37494b06da5464d1), it should be picked up when the docs are regenerated for the next release.

It doesn’t appear to have made it to the stable branch though, so it might have been missed if the next release was to be a point one. @norman – is there a process to when and how the website docs get regenerated or is it a bit ad hoc at the moment?

**Comment by norman** [comment]
@mattwildig It's a bit ad-hoc at the moment; I do it manually when I push a gem. My plan is to switch it off my personal server and over to Github pages, but I haven't done it yet.

**Comment by norman** [comment]
@mattwildig I moved the site over to GH page a while back, and just pushed changes to make sure the site is generated from the stable branch rather than from a version tag, so changes like this will get picked up. To regenerate the website, you need to check out the haml.github.io repository and run `bundle exec rake build sync`.
