### ISSUE TITLE
4.1.0.beta.1 > Illegal nesting with Multiline |

### ISSUE THREAD

**Issue by mickey** [haml/haml#830]
Just bumped the version of haml and launched my tests. Only one error:

```ruby
%p= t(".update_calendar", disable_link: link_to(t(".disable"), disable_car_path), |
  delete_link: link_to(t(".delete"), delete_car_path)).html_safe
```

```shell
ActionView::Template::Error:
       Illegal nesting: content can't be both given on the same line as %p and nested within it.
```

This works on haml 4.0.6.

**Comment by mattwildig** [comment]
Thanks for reporting this. I’ve pushed a fix, so you should be ok in the next release.

Note that in this case the pipe character isn’t needed, since the line is Ruby and ends with a comma it is allowed anyway, i.e. this would work:

```haml
%p= t(".update_calendar", disable_link: link_to(t(".disable"), disable_car_path),
  delete_link: link_to(t(".delete"), delete_car_path)).html_safe
```

@amatsuda I tracked this down to 6f7978a1ebb7937ac3b94b2e4e13c8b8f66ee41b, in particular [this line](https://github.com/haml/haml/commit/6f7978a1ebb7937ac3b94b2e4e13c8b8f66ee41b#diff-4a94cc8fcf4f519d7fadb1953c7fed0cL391), which I have reverted to how it was before. I am assuming this is a corner case that slipped by in that commit and it is safe to revert. Is that right or is there a specific reason for that line that I have missed?

**Comment by mickey** [comment]
I confirm it's now working.
Thanks a lot!
