### ISSUE TITLE
Filter Improvements

### ISSUE THREAD

**Issue by hayesgm** [haml/haml#833]
I have been developing a unique filter for HAML ([something that runs A/b tests for you](https://github.com/hayesgm/vignette)).

I have found so far that filters are pretty restrictive right now in terms of what can be included from the markup itself, and additionally writing filters has made me copy and paste too much code from `Haml::Filters::Base`.  It would be nice to add a few new features:

### Filter attributes

These attributes could be specified in the markup and given to the filter, e.g.

```haml
:javascript{minify: true}
  // ...
```

Adding attributes here would allow filters to receive flags from the markup that are currently lacking (e.g. the :javascript tag cannot be used for 'text/template')

### Improve Haml::Filters::Base

Better context should exist in the core filter hook code.  `render_with_options` isn't given any access to any context or the `compiler` instance.  A good filter is going to have to end up re-writing `compile` by scratch (or via copy and paste, which will cause version conflicts).  It would be great to make this more modular and allow filters to plugin in a standardized fashion.

I would be happy to work on these issues if there is sufficient support.

**Comment by norman** [comment]
> These attributes could be specified in the markup and given to the filter

We've kicked around allowing paramters for filters for a while now, but I've never been convinced enough of their value to implement them. The filter feature is intended for small, restricted embedded usage; to add a small snippet of Javascript in a document, or for prototyping. The feature has never been intended as a major feature with lots of configurability and complexity, in my opinion most of the time when you reach the point where you need to configure filters, it's becaue you're doing something that should be built in some other way than as a Haml filter.

I think a better solution would be to allow filter options to be configured in each Haml filter once at runtime, so that, for example, you could make the :css filter not emit or not emit a `<style>` tag. Ideally the filters could accept a hash of options, delete the ones they need internally (like the option I just described), and then pass the remaining options onto the Tilt template that underlies them to allow the arbitrary configuration options that each engine like Sass, Coffeescript, etc. accepts.

As far as API, I envision something like `Haml::Filters::CSS.options = {foo: 'bar'}`, rather than different configuration options on each invocation of the filter inside the template. This is similar to [what Slim does](http://www.rubydoc.info/gems/slim/frames#Embedded_engines__Markdown______). This is not currently possible but should not be too difficult to implement.

 > Better context should exist in the core filter hook code. render_with_options isn't given any access to any context or the compiler instance.

Very true. I'd be happy to consider a PR that improves this, as long as it's careful not to degrade performance too much.

**Comment by hayesgm** [comment]
I agree that attributes for filters, in general, would be a big improvement for the feature.  In your example of `Haml::Filters::CSS.options = { tag: false }`, wouldn't it make sense to be able to adjust this in the markup, as well.  E.g. `:css{tag: true}`?  This would be a simple merge of the two hashes with the inline attributes taking precedence.

Conceptually, I feel like filters are extensions to the language, and an area that I believe could continue to grow with HAML.  Without being able to access attributes or context, we are hampered to see how they can enhance HAML.  Additionally, as these filters live in gems, new filters will never interfere with the core language.

> Very true. I'd be happy to consider a PR that improves this, as long as it's careful not to degrade performance too much.

I'd be happy to do as much.

**Comment by norman** [comment]
In the interest of getting to "Issues Zero" I'm going to close this issue now since there haven't been any updates for a while, and there's no clear, immediate action we need to take.
