### ISSUE TITLE
Indent is turned on in dev and production

### ISSUE THREAD

**Issue by mainameiz** [haml/haml#837]
According to documentation http://haml.info/docs/yardoc/Haml/Options.html#ugly-instance_method
ugly is must be turned off in production mode, but it is not.

Even if I set it to true it does indentation of json in :coffee filter and I've got `stack error size exceeded` error :-(

I'm trying haml 4.0.6 and 4.1.0.beta1 with rails 4.2.0.

Plz help me. I dont wont to switch back to erb :-(

Thanks for any help!

**Comment by mattwildig** [comment]
The `ugly` option will only affect the HTML generated by HAML – it won’t do anything to the contents of filters.

Where is the error coming from – is it a javascript error? Can you provide a sample that shows the problem?

**Comment by mainameiz** [comment]
This app shows the issue https://github.com/mainameiz/jbuilder_call_stack_size_exceeded

It is a backend error. All output that i put in :coffee filter is indented and this causes the error with stack (see above)

**Comment by mainameiz** [comment]
Sorry, if you replace home/index.html.erb with index.html.haml and it will not work and u will see the error in server console

**Comment by mainameiz** [comment]
I edit the project so now it shows the issue https://github.com/mainameiz/jbuilder_call_stack_size_exceeded

- git clone https://github.com/mainameiz/jbuilder_call_stack_size_exceeded
- rake db:create db:migrate db:seed
- rails s
- open root path

**Comment by mattwildig** [comment]
You have a typo in your `seeds.rb` file. Also, in order to get the same error you’re seeing you need to have `therubyracer` in the `Gemfile` (`jsc` just hangs for me rather than giving an error).

The problem seems to be coming from Coffeescript. You’re giving invalid coffeescript to the filter. You get the same error if you have an Erb file with

```erb
<%= CoffeeScript.compile render(template: "home/index", formats: [:json]) %>
```

(which is roughly equivalent to what is happening in the Haml).

In your original Erb in your repo you render the template as it is surrounded by `script` tags, do you not just want to use the `:javascript` filter rather than the `:coffeescript` one?

**Comment by norman** [comment]
Doesn't seem like there's any action we need to take here; closing issue.
