### ISSUE TITLE
Hash merging should only apply to a configured set of hashes

### ISSUE THREAD

**Issue by norman** [haml/haml#848]
For Haml 5.0, we introduced this change:

> Don't treat the 'data' attribute specially when merging attribute hashes

This feature allows you to nest arbitrary hashes in attributes such as:

``` haml
#foo{:a => {:b => :c}}
```

which will result in the following output:

``` html
<div a-b='c' id='foo'></div>
```

This feature was originally intended to simplify working with data attributes, and we universalized it.

Unfortunately this feature makes it so that any hash that has a variable as an value must always be evaluated at runtime rather than compile time; we can't for example optimize:

``` haml
#foo{:a => @bar}
```

to something like:

``` html
<div a="<%= @bar %>" id='foo'></div>
```

because `@bar` could be a hash.

To avoid this, I think we should have a configurable list of attribute names that accept hashes as attributes. By default, this could be `data` and `aria`.

We should make this change prior to releasing 5.0.

**Comment by mattwildig** [comment]
We couldn’t have made that optimisation anyway, since `@bar` could also be a boolean. We might need a list of boolean attributes as well.

**Comment by norman** [comment]
@mattwildig That's a good point. There's some discussion of the full list of boolean attributes over at kangax/html-minifier#63, they grab the list with:

    curl -s "http://www.w3.org/TR/html51/single-page.html" | grep "attribute boolean"

For 5.0 I'm less concerned about actually optimizing this aspect of Haml's performance - and more concerned with not introducing a new API that makes it impossible do so on the next version. I'm still poking around with the possibility of moving Haml to a Temple-based compiler and thinking about exactly what we want to change now versus later with an eye towards better runtime performance.

**Comment by k0kubun** [comment]
Maybe this issue is aimed to optimize performance? Having configuration may slow down the performance by generating the configuration on template. If it won't be hard-coded, the configuration will be just trade-off.

And, in https://github.com/haml/haml/pull/904, I could generate reasonably faster code.

## input
```haml
#foo{:a => @bar}
```

## output

```rb
_hamlout.buffer << ("<div".freeze);; 
_haml_attribute_compiler1 = (@bar); 
case (_haml_attribute_compiler1); 
when Hash; _hamlout.buffer << ((_hamlout.attributes({ "a".freeze => _haml_attribute_compiler1 }, nil)).to_s);; 
when true; _hamlout.buffer << (" a".freeze);; 
when false, nil; 
else; 
  _hamlout.buffer << (" a='".freeze);; 
  _hamlout.buffer << (::Haml::Helpers.html_escape((_haml_attribute_compiler1)));; 
  _hamlout.buffer << ("'".freeze);; 
end; 
_hamlout.buffer << (" id='foo'></div>\n".freeze);
```

This is almost ideal generated code. Introducing such configurations may remove only `when Hash`, `when true` and `When false, nil`. Now it doesn't have large impact and currently it's not Haml's bottleneck.

So, I think it's a good time to close this issue. We need to tackle another part if we want to optimize Haml.
