### ISSUE TITLE
Haml Truck Factor

### ISSUE THREAD

**Issue by gavelino** [haml/haml#854]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Haml** and obtained a value of **3**.

The developers responsible for this TF are:

Natalie Weizenbaum - author of 51% of the files
Nathan Weizenbaum - author of 39% of the files
Norman Clarke - author of 32% of the files

To validate our results, we would like to ask **Haml** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Haml**?

(b) Do you agree that **Haml** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Haml** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by hcatlin** [comment]
Natalie was previously known as Nathan Weizenbaum, so they are the same person.

Also, Natalie left the project about 4 years ago, if I recall, and then Norman took over the project.

It’s mostly stable at this point, so not a lot of major issues if Norman left (I still love you Norman and love your great work!), as it’s all pretty well tested and someone could figure out whatever the issue was… probably. ;)

**Comment by gavelino** [comment]
Thank you.
