### ISSUE TITLE
typo completely kills ruby process (2.3.0)

### ISSUE THREAD

**Issue by KevinColemanInc** [haml/haml#863]
I noticed if you put a `=` sign instead of a `:` in the attributes of a tag, it complete kills the ruby process.

`%a{href:"/"} home` ok

`%a{href="/"} home` FAIL

`[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html`

It would be nice if I didn't have to restart my server if I typo a character.

**Comment by mattwildig** [comment]
There must be something else going on here. I get (with Ruby 2.3.0):

```
~ $  haml
%a{href="/"}

Exception on line 202: undefined method `map' for "/":String
Did you mean?  tap
  Use --trace for backtrace.
```
How are you using Haml here? Is this part of a Rails app?

**Comment by k0kubun** [comment]
As written in the message, this is `a bug in the Ruby interpreter or extension libraries` and not Haml's one. Calling `#map` for `String` is broken and Haml may not do that.

Possibly other gems having extension may affect. Please give us the contents of `Gemfile.lock` or the result of `gem list`.

And since this issue is not responded, closing.
