### ISSUE TITLE
Cross-site Scripting When Outputting Params Hash

### ISSUE THREAD

**Issue by mccabe615** [haml/haml#891]
During a security review of an application that uses HAML I discovered that HAML doesn't properly encode the params hash when a specific key isn't used. I've created a sample application with instructions of how to recreate the issue. It seems HAML doesn't properly encode the params hash key when the full hash is included in a template as shown below.

```
-# not properly encoded
          %input{:type=>"hidden", :data=>params, :id=>"current_tab"}
-# properly encoded
          %input{:type=>"hidden", :data=>params[:id], :id=>"current_tab"}
          %p
```

[Example app](https://github.com/mccabe615/haml_xss_example)

**Comment by mattwildig** [comment]
The underlying issue here seems to be that although we [escape attribute _values_](https://github.com/haml/haml/blob/ed361008151d14c1168a7804f7f2a0d4a414e423/lib/haml/compiler.rb#L444-L451), we don’t do anything for attribute _names_.

Here’s an example:

```haml
%input{"><script>alert(1)</script>" => 'foo'}
```
which produces:
```html
<input ><script>alert(1)</script>='foo'>
```
I guess the assumption was attribute names wouldn’t be dynamically created, they would be part of the Haml source and only the values would vary.

I don’t know how we should handle this. I don’t think just HTML escaping attribute names  would be correct, as they are not “content” in the same way as text or attribute values are. The [HTML spec says this about attribute names](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2):

> Attribute names must consist of one or more characters other than the space characters, U+0000 NULL, U+0022 QUOTATION MARK ("), U+0027 APOSTROPHE ('), U+003E GREATER-THAN SIGN (>), U+002F SOLIDUS (/), and U+003D EQUALS SIGN (=) characters, the control characters, and any characters that are not defined by Unicode.

The obvious solution would be to just strip out those characters from attribute names when processing attributes (perhaps issue a warning if any are found). I can’t see any way of restricting that processing to just “dynamic” attributes though, so it may involve a performance hit.

**Comment by k0kubun** [comment]
> The obvious solution would be to just strip out those characters from attribute names when processing attributes (perhaps issue a warning if any are found).

I think stripped attribute name is not intentional for everybody. `params` is user's input. Thus this request should be 4XX IMO. Rendering user's input as attribute name is definitely vulnerable, which is not Haml's fault.

So, the ideal behavior of Haml's attribute may be raising exception when invalid name (HTML-escapable string is included), rescuing it by Rails application and responding with 4XX.
