### ISSUE TITLE
Haml 5.0 on windows: Permission denied @ rb_file_s_symlink

### ISSUE THREAD

**Issue by francesco-loreti** [haml/haml#919]
When I install 5.0 from 4.0.7, on windows, I receive this error:
`ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (test/templates/standard.haml, C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/haml-5.0.0/test/templates/standard_ugly.haml)`

**Comment by k0kubun** [comment]
Because haml-4.0.7 has symlink in original repository but the package on rubygems.org didn't have symlink (had copied file), maybe that's caused by rubygems changes https://github.com/rubygems/rubygems/pull/1418 https://github.com/rubygems/rubygems/pull/1209. nobu says symlink is supported from Ruby 2.3 but it looks that it doesn't work on your environment.

Anyway, such symlink is unnecessary for gem package, thus I'll just remove it.

**Comment by amatsuda** [comment]
@francesco-loreti Just released haml 5.0.1 gem and I confirmed that it's installable on Windows. Could you try this new version?

**Comment by francesco-loreti** [comment]
@amatsuda Perfect job
