### ISSUE TITLE
Javascript escaping invalid, generates SyntaxError: expected expression, got '&'

### ISSUE THREAD

**Issue by javinto** [haml/haml#940]
The 5.0.0 release notes refers to: 

> HTML escape interpolated code in filters. #770 (Matt Wildig)
> ```
> :javascript
>     #{JSON.generate(foo: "bar")}
>   Haml 4 output: {"foo":"bar"}
>   Haml 5 output: {&quot;foo&quot;:&quot;bar&quot;}
> ```

However, I have (Haml 5.0.1):

```
:javascript
  var list1= ["a", 'b', 'c'];
  var hash1= {a: "a", b: 'b'};
  var list2= #{JSON.generate( [:a, :b, :c])};
  var hash2= #{JSON.generate(foo: "bar")};
```
In the browser this results into:

```
<script>
  var list1= ["a", 'b', 'c'];
  var hash1= {a: "a", b: 'b'};
  var list2= [&quot;a&quot;,&quot;b&quot;,&quot;c&quot;];
  var hash2= {&quot;foo&quot;:&quot;bar&quot;};
</script>
```

The browsers runs into an error on line 4 (list2) and 5 (hash2): 

> SyntaxError: expected expression, got '&'

**Comment by k0kubun** [comment]
This is intentional, not a bug. You should fix template like this (using data attribute) https://github.com/sferik/rails_admin/pull/2870 or disable HTML escape globally.

**Comment by javinto** [comment]
Okay, a pitty, but I can do this. 

However, the code giving me this problem is like:

:javascript
   var my_var=Array( #{ruby_array}); 

In the HAML Reference file it says: "Currently, filters ignore the :escape_html <http://haml.info/docs/yardoc/Haml/Options.html#escape_html-instance_method> option. This means that #{} interpolation within filters is never HTML-escaped."

Does this mean that the documentation is outdated?

**Comment by k0kubun** [comment]
> Does this mean that the documentation is outdated?

Yes, definitely. I fixed it https://github.com/haml/haml/commit/965e66eb6ba5bbd8b4d89ba8cc60e2a05c658855. Thank you for reporting it.

**Comment by marz0** [comment]
@k0kubun is it possible to set the `escape_html` option for a particular filter? For instance,

```ruby
:javascript{ escape_html: false }
```

Just looking to keep the same behavior as before.

**Comment by k0kubun** [comment]
> Just looking to keep the same behavior as before.

In Rails, you can call html_safe to value. Otherwise no idea.

**Comment by praxeum** [comment]
I still don't understand how this works, or why it was introduced. What could previously be done with:

```ruby
:javascript
  var array = #{@user.all.to_json}
```

...now results in a broken JSON output. Even if we ignore the why, I still don't know how to use `:escape_html`? Should it be used like in the above comment, i.e:

```ruby
:javascript{ escape_html: false }
  var array = #{@user.all.to_json}
```

Or does `:escape_html` go somewhere else?

**Comment by k0kubun** [comment]
It seems that you use ActiveRecord and it's likely that you can use `html_safe` or `raw` as I said. Why don't you use that? Did you check https://github.com/haml/haml/pull/770?

```haml
:javascript
  var array = #{@user.all.to_json.html_safe}
```

> Even if we ignore the why, I still don't know how to use :escape_html?

```rb
Haml::Template.options[:escape_html] = false
```

This would also solve your problem if you're using Rails.

> I still don't understand how this works, or why it was introduced. 

That's because there are possibly vulnerable cases in some string interpolation.

```haml
- foo = "null;</script> ANY HTML HERE <script>"
:javascript
  var array = #{foo}
```

Does it make sense?

**Comment by javinto** [comment]
The way I solved it, is to set somewhere in your config:

Haml::Template.options[:escape_html] = false

This will give you the ‘old way’.

**Comment by praxeum** [comment]
Ah nice, yeah that makes sense. Although `html_safe` is not an option for me, it fails to render correctly because of how I filter the output with includes:

```ruby
:javascript
  var array = #{@available_shifts.to_json(:include => { :ward => {:include => :location} })}
```

If I add `html_safe` to the above output, like so:

```ruby
:javascript
  var array = #{@available_shifts.to_json.html_safe(:include => { :ward => {:include => :location} })}
```

...I get a `Uncaught reference` error in console.

I'll use the `Haml::Template.options[:escape_html] = false`, seems the best option.

**Comment by k0kubun** [comment]
Please try one of followings if your application is on production:

```rb
:javascript
  var array = #{@available_shifts.to_json(:include => { :ward => {:include => :location} }).html_safe}
```

```rb
:javascript
  var array = #{raw @available_shifts.to_json(:include => { :ward => {:include => :location} })}
```

**Comment by praxeum** [comment]
Tried both of those and no difference. Adding `html_safe` to after the include makes no difference to the JSON (still rendered with "&quote;"), and adding `raw` before the render also makes no difference. Both result in the same as not having them at all.

**Comment by k0kubun** [comment]
Hmm, it sounds like another issue. Let me check.

**Comment by praxeum** [comment]
Also worth noting that I can't actually just put

```javascript
var array = #{@available_shifts.to_json(:include => { :ward => {:include => :location} })}
```

I have to wrap the Rails section in quotes for it to do anything, i.e

```javascript
var array = "#{@available_shifts.to_json(:include => { :ward => {:include => :location} })}"
```

**Comment by k0kubun** [comment]
> var array = "#{@available_shifts.to_json(:include => { :ward => {:include => :location} })}"

You need string in `array`, not raw array? It would be broken if the json includes double quotes. I would write it you need JSON in string:

```rb
:javascript
  var array = #{@available_shifts.to_json(:include => { :ward => {:include => :location} })};
```

<hr>

Anyway, I tried Haml 5.0.1 and `html_safe` on Rails, and it just worked. Probably you do or have something wrong.

**Comment by praxeum** [comment]
Ok thanks, I'll take another look.

**Comment by k0kubun** [comment]
^^^ Wrong paste, please reload above

**Comment by Justin-Maxwell** [comment]
New to Haml...

TL;DR - **in 'production' haml/template.rb forces :escape_html = true**, so setting it false in the initializer doesn't work! 

After hours of trying to work out how to get a Ruby hash into a JavaScript object within a :javascript block (**because should be easy, right?**), and then, with reluctance, setting the global :escape_html option (because, outside of a few places, like :javascript, encoding to entities makes sense, right?)

I finally had hashes in objects - or so I thought... 

Deploy to the server, and all the &quot; I has been fighting suddenly came back to haunt me.  Gone in development, but not in production.  For some reason even ...
`Haml::Template.options[:escape_html] = false` 
... wasn't working.  I was not a happy hamler!

So anyway, a long while later of running production locally with breakpoints to narrow down what was going on - it turns out that, during initialization, in production, there's a line towards the end of 
`/haml-5.0.2/lib/haml/template.rb` that gets processed right after `initializers/haml.rb` that says:
`Haml::Template.options[:escape_html] = true`

:-/

But, fortunately, in this thread, I have learn't of 'html_safe' - something not mentioned as far as I can tell anywhere in the docs?

And now I know that, in a `:javascript` block `var = #{hash.to_json.html_safe}` works fine.  Still seems mildly absurdly verbose to have to put that in everywhere.  I'd think a Rails-oriented HTML page generator would deal with Hash→JS-Object without requiring much prior-knowledge or thought.  But if that's how it's to be...

...please add a mention of hash.to_json.html_safe in a couple of places, e.g.

This example in the Ruby Interpolation: #{} section of the reference:
```
:javascript
  $(document).ready(function() {
    alert(#{@message.to_json});
  });
```

... perhaps the FAQ, and also mention html_safe in the [Escaping HTML] section of the docs, to make it easier for the noobs who come after me...  :-)

**Comment by baelter** [comment]
What about non rails users that don't have raw or html_safe??

**Comment by k0kubun** [comment]
Use data attribute. I've never experienced data attribute couldn't be used for just injecting JSON from Ruby world.

**Comment by baelter** [comment]
example please

**Comment by k0kubun** [comment]
https://github.com/sferik/rails_admin/pull/2870

**Comment by baelter** [comment]
What if i want it as a js variable?

**Comment by k0kubun** [comment]
```js
var variable = document.getElementById("foo").getAttribute("data-bar");
// or possibly
var variable = JSON.parse(document.getElementById("foo").getAttribute("data-bar"));
```

**Comment by baelter** [comment]
So the suggested solution is something like:

```
#myData{style: "display: none", 'data-mydata': myData.to_json}
:javascript
  var myData = JSON.parse(document.querySelector('#myData').dataset.myData);
```

jiiikes

**Comment by k0kubun** [comment]
Yes. Sorry for taking your time to migrate code in that way.

**Comment by jeremywadsack** [comment]
I second @Justin-Maxwell's suggestion of documentation updates. This hit us with an update to `haml-rails` which happened to pull in `haml` 5.x and I didn't even notice that there would be a change. In testing we never saw this until we pushed to production. (Thank you, @k0kubun for maintaining a `CHANGELOG`, which `haml-rails` doesn't have.)

For Rails apps and JSON, using `raw (...)` or adding `.html_safe` is just marking the content as "safe". That assumes you've already cleared it of tainted data. This matches the old behavior but you can do better with [`#json_escape`](http://api.rubyonrails.org/classes/ERB/Util.html#method-c-json_escape):

```
:javascript
  $(document).ready(function() {
    alert(#{raw json_escape(@message.to_json)});
  });
```

**Comment by wjordan** [comment]
Following up on https://github.com/haml/haml/issues/940#issuecomment-325833327:
> TL;DR - in 'production' haml/template.rb forces :escape_html = true, so setting it false in the initializer doesn't work!

I managed to reproduce this consistently, and it actually seems like a subtle change in behavior introduced in Haml 5 that did not behave the same in Haml 4. I'm not sure this change in behavior is intentional, and this subtle difference can be quite dangerous considering its production-environment-specific behavior. I will follow-up on this in a linked issue.

**Comment by wjordan** [comment]
For others still facing migration pains related to this issue, I've opened a PR #984 that adds an `:escape_interpolated_html` option for backwards compatibility with v4. Using the PR, set `Haml::Template.options[:escape_interpolated_html] = false` in an initializer to get the old version 4 behavior without needing to refactor the rest of your application code.

**Comment by eric-norcross** [comment]
+1

**Comment by shepmaster** [comment]
I wrote a little script to help us find cases of interpolation inside of HAML `:javascript` filters:

```ruby
require 'haml'

# Couldn't get `Haml::Util.handle_interpolation` to work *shrug*
def scan_for_escape(t)
    scanner = StringScanner.new(t)
    yield scanner while scanner.scan_until(/#\{/)
end

def check(node, fname)
  if node.type == :filter && node.value[:name] == "javascript"
    interpolations = []

    scan_for_escape(node.value[:text]) do |scanner|
      start_pos = scanner.pos
      Haml::Util.balance(scanner, '{', '}', 1)
      end_pos = scanner.pos
      matching = scanner.string[start_pos...end_pos]
      interpolations << matching
    end

    not_safe = interpolations.reject { |i| i.match /.to_json.html_safe\s*}\z/ }

    unless not_safe.empty?
      puts "#{fname}:#{node.line}:"
      not_safe.each do |b|
        puts "  #{b}"
      end
    end
  else
    node.children.each do |n|
      check(n, fname)
    end
  end
end

ARGV.each do |fname|
  file_contents = File.read(fname)
  node = Haml::Parser.new({}).call(file_contents)
  check(node, fname)
end
```

run as something like `bundle exec ruby haml_check.rb $(find . -name '*haml')`

In our case, we wanted to make sure every interpolation ended with `to_json.html_safe`; you may need to tweak the script for your own case.
