### ISSUE TITLE
The character sequence `#$` is not parsed correctly

### ISSUE THREAD

**Issue by audenaert** [haml/haml#975]
We recently updated HAML from 4.0.6 to 5.0.4. Our JS that makes use of the ES2015 templating syntax, along the lines of `$('a', `#${tab_id}`).tab('activate all', tab_id);` is no longer properly handled. 

The resulting conversion produces an error stating that there is `no implicit conversion of nil into String`. Testing a few different scenarios revealed that this is specific to the `#$` pattern and produces the same error wherever it is used. For example, `$('a', `#\${tab_id}`).tab('activate all', active_step);` renders properly (though clearly doesn't produce the desired CSS selector) but including `#$` as text to be rendered on the page (no JS) breaks.

We are using Ruby 2.4.3 and Rails 4.2.10.

**Comment by hcatlin** [comment]
@audenaert this is using the `:javascript` filter?

```
:javascript
  $('a',#${tab_id}).tab('activate all', tab_id);
```

**Comment by audenaert** [comment]
Both with and without `:javascript` filter. I set up a minimal test case with the following files (apologies for the poorly formatted code blocks in the OP):

```
%h1 Pages#works
%p
  This page does render because of the following (note the space): # $
%p
  But see <a href="#{pages_broken_path}">this page</a> and <a href="#{pages_also_broken_path}">this one</a> for
  examples of the broken behavior.
```

and 

```
%h1 Pages#broken
%p
 This page does not render because of the following: #$
```

The following also breaks:
```
%h1 Pages#also_broken
%p
 This page does not render because of the following javascript

:javascript
  const tab_id = 'bob';
  Console.log(`#${tab_id}`)
```

**Comment by mattwildig** [comment]
This looks like it was caused by  a [change to make Haml interpolation more closely match Ruby interpolation](https://github.com/haml/haml/commit/fb9a2b19b3f0591cb062de902965abfa6d0c0036). In Ruby, as well as interpolating with the common `"... #{ Ruby code here } ..."`, you can also use `"... #@attribute_variable ..."` and `"... #$global_variable ..."`, and Haml now also looks for those patterns.

In this case the `#$` triggers the global parsing code, but since there is no identifier it’s causing a nil pointer bug.

This seems to be a fairly obscure feature, I may have been a bit overzealous implementing it. Perhaps we need to detect this at parse time and either give a better worded error or treat it as a literal `#$`.

The current fix/workaround would be to escape the `#` with a `\`:

```haml
%h1 Pages#no_longer_broken
%p
 This page now does render with the following: \#$
```

which produces:

```html
<h1>Pages#no_longer_broken</h1>
<p>
This page now does render with the following: #$
</p>
```

**Comment by hcatlin** [comment]
That seems like a dangerous feature. Especially when the more explicit `#{$var}` covers the case pretty well.

I can see more of a use for `#@` than `#$`

How about we remove the support for `#$` and if `#@` fails to resolve, we can raise a more descriptive error?

**Comment by lazylester** [comment]
in order to inform your prioritization of fixing this issue... it is triggered when interpolating a dynamically assigned jQuery selector inside the :javascript filter, like
````haml
#container
:javascript
  var identifier = "container"
  $(`#${identifier}`).text("foo")
````
